defmodule Blackboex.Apis.Templates do
  @moduledoc """
  Template library and API creation from templates.

  Provides the template catalogue (list, get, categories) and creation functions
  that instantiate APIs from templates or generation results.
  """

  alias Blackboex.Apis
  alias Blackboex.Apis.Files
  alias Blackboex.CodeGen.GenerationResult
  alias Blackboex.Samples.Manifest

  @type template :: %{
          id: String.t(),
          name: String.t(),
          description: String.t(),
          category: String.t(),
          icon: String.t(),
          method: String.t(),
          template_type: String.t(),
          files: %{
            handler: String.t(),
            helpers: String.t(),
            request_schema: String.t(),
            response_schema: String.t(),
            test: String.t(),
            readme: String.t()
          },
          param_schema: map(),
          example_request: map(),
          example_response: map(),
          validation_report: map()
        }

  @category_order [
    "AI Agent Tools",
    "Webhooks",
    "Mocks",
    "Prototypes"
  ]

  @doc "Returns all available templates."
  @spec list() :: [template()]
  def list, do: Manifest.list_by_kind(:api)

  @doc "Returns a template by its id, or nil if not found."
  @spec get(String.t()) :: template() | nil
  def get(id) do
    Manifest.get_by_kind_and_id(:api, id)
  end

  @doc "Returns the unique sorted list of categories present in the template library."
  @spec categories() :: [String.t()]
  def categories do
    present =
      list()
      |> Enum.map(& &1.category)
      |> Enum.uniq()
      |> MapSet.new()

    Enum.filter(@category_order, &MapSet.member?(present, &1))
  end

  @doc "Returns templates grouped by category, in canonical category order."
  @spec list_by_category() :: [{String.t(), [template()]}]
  def list_by_category do
    grouped = Enum.group_by(list(), & &1.category)

    @category_order
    |> Enum.filter(&Map.has_key?(grouped, &1))
    |> Enum.map(fn cat -> {cat, Map.fetch!(grouped, cat)} end)
  end

  # ── API Creation from Templates ─────────────────────────────

  @doc """
  Creates an API and seeds it with default skeleton files based on its template_type.

  Creates `/src/handler.ex` with a template-appropriate skeleton and
  `/test/handler_test.ex` as an empty placeholder.
  """
  @spec create_api_with_files(map()) ::
          {:ok, Apis.Api.t()}
          | {:error, Ecto.Changeset.t()}
          | {:error, :limit_exceeded, map()}
  def create_api_with_files(attrs) do
    case Apis.create_api(attrs) do
      {:ok, api} ->
        template_type = to_string(api.template_type || "computation")
        handler_content = default_handler_content(template_type)

        Files.create_file(api, %{
          path: "/src/handler.ex",
          content: handler_content,
          file_type: "source",
          source: "scaffold"
        })

        Files.create_file(api, %{
          path: "/test/handler_test.ex",
          content: "# Tests will be generated by the AI agent",
          file_type: "test",
          source: "scaffold"
        })

        Files.create_file(api, %{
          path: "/README.md",
          content:
            "# #{api.name}\n\nDocumentation will be generated after code generation completes.",
          file_type: "doc",
          source: "scaffold"
        })

        {:ok, api}

      error ->
        error
    end
  end

  @doc """
  Creates an API from a pre-built template, populating all artefacts
  (6 source files + 4 Api schema fields) without going through the LLM pipeline.

  Returns `{:ok, api}` with `status: "compiled"` on success.
  Returns `{:error, :template_not_found}` if the template id is unknown.
  """
  @spec create_api_from_template(map(), String.t()) ::
          {:ok, Apis.Api.t()}
          | {:error, :template_not_found}
          | {:error, Ecto.Changeset.t()}
          | {:error, :limit_exceeded, map()}
  def create_api_from_template(attrs, template_id) do
    case get(template_id) do
      nil ->
        {:error, :template_not_found}

      template ->
        attrs =
          Map.merge(attrs, %{
            template_id: template_id,
            template_type: "computation",
            status: "compiled",
            method: template.method,
            param_schema: template.param_schema,
            example_request: template.example_request,
            example_response: template.example_response,
            validation_report: template.validation_report
          })

        case Apis.create_api(attrs) do
          {:ok, api} ->
            files = template.files

            Files.create_file(api, %{
              path: "/src/handler.ex",
              content: files.handler,
              file_type: "source",
              source: "template"
            })

            Files.create_file(api, %{
              path: "/src/helpers.ex",
              content: files.helpers,
              file_type: "source",
              source: "template"
            })

            Files.create_file(api, %{
              path: "/src/request_schema.ex",
              content: files.request_schema,
              file_type: "source",
              source: "template"
            })

            Files.create_file(api, %{
              path: "/src/response_schema.ex",
              content: files.response_schema,
              file_type: "source",
              source: "template"
            })

            Files.create_file(api, %{
              path: "/test/handler_test.ex",
              content: files.test,
              file_type: "test",
              source: "template"
            })

            Files.create_file(api, %{
              path: "/README.md",
              content: files.readme,
              file_type: "doc",
              source: "template"
            })

            {:ok, api}

          error ->
            error
        end
    end
  end

  @spec create_api_from_generation(
          GenerationResult.t(),
          Ecto.UUID.t(),
          integer(),
          String.t(),
          Ecto.UUID.t()
        ) ::
          {:ok, Apis.Api.t()} | {:error, Ecto.Changeset.t()}
  def create_api_from_generation(
        %GenerationResult{} = result,
        organization_id,
        user_id,
        name,
        project_id
      ) do
    Apis.create_api(%{
      name: name,
      description: result.description,
      template_type: to_string(result.template),
      method: result.method || "POST",
      organization_id: organization_id,
      project_id: project_id,
      user_id: user_id,
      example_request: result.example_request,
      example_response: result.example_response,
      param_schema: result.param_schema
    })
  end

  # ── Private ─────────────────────────────────────────────────

  defp default_handler_content("crud") do
    "def handle_list(params), do: []\n" <>
      "def handle_get(id, params), do: %{id: id}\n" <>
      "def handle_create(params), do: %{created: true}\n" <>
      "def handle_update(id, params), do: %{updated: true}\n" <>
      "def handle_delete(id), do: %{deleted: true}"
  end

  defp default_handler_content("webhook") do
    "def handle_webhook(payload) do\n  %{received: true}\nend"
  end

  defp default_handler_content(_computation) do
    "def handle(params) do\n  %{result: \"ok\"}\nend"
  end
end
