defmodule Blackboex.PlaygroundAgent.CodeParserTest do
  use ExUnit.Case, async: true

  alias Blackboex.PlaygroundAgent.CodeParser

  describe "extract_code/1" do
    test "extracts code from an ```elixir fence" do
      content = """
      Here it is:
      ```elixir
      IO.puts("hi")
      ```
      Summary: prints hi
      """

      assert {:ok, "IO.puts(\"hi\")"} = CodeParser.extract_code(content)
    end

    test "also accepts ```ex fence" do
      content = "```ex\nx = 1\n```"
      assert {:ok, "x = 1"} = CodeParser.extract_code(content)
    end

    test "falls back to generic fence when no language specified" do
      content = "```\nIO.puts(:ok)\n```"
      assert {:ok, "IO.puts(:ok)"} = CodeParser.extract_code(content)
    end

    test "returns error when no fence is present" do
      assert {:error, :no_code_block} = CodeParser.extract_code("only prose, no code")
    end

    test "returns the first fence when multiple are present" do
      content = """
      ```elixir
      first
      ```
      and more:
      ```elixir
      second
      ```
      """

      assert {:ok, "first"} = CodeParser.extract_code(content)
    end
  end

  describe "extract_summary/1" do
    test "picks up a Summary: line" do
      content = "```elixir\nx\n```\nSummary: adds two numbers"
      assert "adds two numbers" = CodeParser.extract_summary(content)
    end

    test "defaults when no summary is present" do
      assert "Code generated by the agent" = CodeParser.extract_summary("```elixir\nx\n```")
    end
  end
end
